Fixes an error in the reorder:
Traceback (most recent call last):
  File "eggbot_reorder.py", line 168, in <module>
    e.affect()
  File "/usr/share/inkscape/extensions/inkex.py", line 283, in affect
    self.effect()
  File "eggbot_reorder.py", line 162, in effect
    "Have a nice day!".format(air_distance_default, air_distance_ordered, improvement_pct)))
ValueError: Unknown format code 'd' for object of type 'float'

Changed the format string to a float. Plus explicitly cast air_distance_ordered & air_distance_default to floats for previous versions that may have used ints.

Also saw this TODO and fixed it to start out at infinity instead of $reallybignumber.

    min_distance = 100000000  # TODO put something else here better?
    min_distance = float('inf') # Set the inital min distance to infinity.